# Arquivo: configs/random_forest.yaml

model_name: "RandomForestClassifier"
data_path: "data/dataset_saude_brasil.csv" 
save_dir: "artifacts/random_forest/"     

# Parâmetros estáticos que não entram na busca do GridSearch
static_params:
  random_state: 42
  n_jobs: -1

# Grade de hiperparâmetros para a busca com GridSearchCV
hyperparameter_grid:
  n_estimators: [50, 100, 200]
  min_samples_split: [10, 20, 40]
  min_samples_leaf: [5, 10, 20]
  max_depth: [10, 15, 20]
  max_features: ['sqrt', 0.5]
  bootstrap: [True] 